import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Sidebar from '@/components/Sidebar';
import AppSidebar from '@/components/Sidebar';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Final Interview',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`max-w-[1300px] overflow-x-hidden p-5 mx-auto ${geistSans.variable} ${geistMono.variable} antialiased flex`}>
        {/* <SidebarProvider>
          <AppSidebar /> */}
        {/* <SidebarTrigger /> */}
        {children}
        {/* </SidebarProvider> */}
      </body>
    </html>
  );
}
